/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/_index'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as IndexIndexImport } from './routes/_index/index'
import { Route as IndexZonasDeTreinoImport } from './routes/_index/zonas-de-treino'
import { Route as IndexTestesImport } from './routes/_index/testes'
import { Route as IndexPlanejamentoImport } from './routes/_index/planejamento'
import { Route as IndexOnboardingImport } from './routes/_index/onboarding'
import { Route as IndexNovoTreinoImport } from './routes/_index/novo-treino'
import { Route as IndexClientsImport } from './routes/_index/clients'
import { Route as IndexSettingsIndexImport } from './routes/_index/settings/index'
import { Route as IndexCalculadoraIndexImport } from './routes/_index/calculadora/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/_index',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexIndexRoute = IndexIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IndexRoute,
} as any)

const IndexZonasDeTreinoRoute = IndexZonasDeTreinoImport.update({
  id: '/zonas-de-treino',
  path: '/zonas-de-treino',
  getParentRoute: () => IndexRoute,
} as any)

const IndexTestesRoute = IndexTestesImport.update({
  id: '/testes',
  path: '/testes',
  getParentRoute: () => IndexRoute,
} as any)

const IndexPlanejamentoRoute = IndexPlanejamentoImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => IndexRoute,
} as any)

const IndexOnboardingRoute = IndexOnboardingImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => IndexRoute,
} as any)

const IndexNovoTreinoRoute = IndexNovoTreinoImport.update({
  id: '/novo-treino',
  path: '/novo-treino',
  getParentRoute: () => IndexRoute,
} as any)

const IndexClientsRoute = IndexClientsImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => IndexRoute,
} as any)

const IndexSettingsIndexRoute = IndexSettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => IndexRoute,
} as any)

const IndexCalculadoraIndexRoute = IndexCalculadoraIndexImport.update({
  id: '/calculadora/',
  path: '/calculadora/',
  getParentRoute: () => IndexRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_index': {
      id: '/_index'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/_index/clients': {
      id: '/_index/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof IndexClientsImport
      parentRoute: typeof IndexImport
    }
    '/_index/novo-treino': {
      id: '/_index/novo-treino'
      path: '/novo-treino'
      fullPath: '/novo-treino'
      preLoaderRoute: typeof IndexNovoTreinoImport
      parentRoute: typeof IndexImport
    }
    '/_index/onboarding': {
      id: '/_index/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof IndexOnboardingImport
      parentRoute: typeof IndexImport
    }
    '/_index/planejamento': {
      id: '/_index/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof IndexPlanejamentoImport
      parentRoute: typeof IndexImport
    }
    '/_index/testes': {
      id: '/_index/testes'
      path: '/testes'
      fullPath: '/testes'
      preLoaderRoute: typeof IndexTestesImport
      parentRoute: typeof IndexImport
    }
    '/_index/zonas-de-treino': {
      id: '/_index/zonas-de-treino'
      path: '/zonas-de-treino'
      fullPath: '/zonas-de-treino'
      preLoaderRoute: typeof IndexZonasDeTreinoImport
      parentRoute: typeof IndexImport
    }
    '/_index/': {
      id: '/_index/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexIndexImport
      parentRoute: typeof IndexImport
    }
    '/_index/calculadora/': {
      id: '/_index/calculadora/'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof IndexCalculadoraIndexImport
      parentRoute: typeof IndexImport
    }
    '/_index/settings/': {
      id: '/_index/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof IndexSettingsIndexImport
      parentRoute: typeof IndexImport
    }
  }
}

// Create and export the route tree

interface IndexRouteChildren {
  IndexClientsRoute: typeof IndexClientsRoute
  IndexNovoTreinoRoute: typeof IndexNovoTreinoRoute
  IndexOnboardingRoute: typeof IndexOnboardingRoute
  IndexPlanejamentoRoute: typeof IndexPlanejamentoRoute
  IndexTestesRoute: typeof IndexTestesRoute
  IndexZonasDeTreinoRoute: typeof IndexZonasDeTreinoRoute
  IndexIndexRoute: typeof IndexIndexRoute
  IndexCalculadoraIndexRoute: typeof IndexCalculadoraIndexRoute
  IndexSettingsIndexRoute: typeof IndexSettingsIndexRoute
}

const IndexRouteChildren: IndexRouteChildren = {
  IndexClientsRoute: IndexClientsRoute,
  IndexNovoTreinoRoute: IndexNovoTreinoRoute,
  IndexOnboardingRoute: IndexOnboardingRoute,
  IndexPlanejamentoRoute: IndexPlanejamentoRoute,
  IndexTestesRoute: IndexTestesRoute,
  IndexZonasDeTreinoRoute: IndexZonasDeTreinoRoute,
  IndexIndexRoute: IndexIndexRoute,
  IndexCalculadoraIndexRoute: IndexCalculadoraIndexRoute,
  IndexSettingsIndexRoute: IndexSettingsIndexRoute,
}

const IndexRouteWithChildren = IndexRoute._addFileChildren(IndexRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof IndexRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/clients': typeof IndexClientsRoute
  '/novo-treino': typeof IndexNovoTreinoRoute
  '/onboarding': typeof IndexOnboardingRoute
  '/planejamento': typeof IndexPlanejamentoRoute
  '/testes': typeof IndexTestesRoute
  '/zonas-de-treino': typeof IndexZonasDeTreinoRoute
  '/': typeof IndexIndexRoute
  '/calculadora': typeof IndexCalculadoraIndexRoute
  '/settings': typeof IndexSettingsIndexRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/clients': typeof IndexClientsRoute
  '/novo-treino': typeof IndexNovoTreinoRoute
  '/onboarding': typeof IndexOnboardingRoute
  '/planejamento': typeof IndexPlanejamentoRoute
  '/testes': typeof IndexTestesRoute
  '/zonas-de-treino': typeof IndexZonasDeTreinoRoute
  '/': typeof IndexIndexRoute
  '/calculadora': typeof IndexCalculadoraIndexRoute
  '/settings': typeof IndexSettingsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_index': typeof IndexRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_index/clients': typeof IndexClientsRoute
  '/_index/novo-treino': typeof IndexNovoTreinoRoute
  '/_index/onboarding': typeof IndexOnboardingRoute
  '/_index/planejamento': typeof IndexPlanejamentoRoute
  '/_index/testes': typeof IndexTestesRoute
  '/_index/zonas-de-treino': typeof IndexZonasDeTreinoRoute
  '/_index/': typeof IndexIndexRoute
  '/_index/calculadora/': typeof IndexCalculadoraIndexRoute
  '/_index/settings/': typeof IndexSettingsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/register'
    | '/clients'
    | '/novo-treino'
    | '/onboarding'
    | '/planejamento'
    | '/testes'
    | '/zonas-de-treino'
    | '/'
    | '/calculadora'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/clients'
    | '/novo-treino'
    | '/onboarding'
    | '/planejamento'
    | '/testes'
    | '/zonas-de-treino'
    | '/'
    | '/calculadora'
    | '/settings'
  id:
    | '__root__'
    | '/_index'
    | '/login'
    | '/register'
    | '/_index/clients'
    | '/_index/novo-treino'
    | '/_index/onboarding'
    | '/_index/planejamento'
    | '/_index/testes'
    | '/_index/zonas-de-treino'
    | '/_index/'
    | '/_index/calculadora/'
    | '/_index/settings/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_index",
        "/login",
        "/register"
      ]
    },
    "/_index": {
      "filePath": "_index.tsx",
      "children": [
        "/_index/clients",
        "/_index/novo-treino",
        "/_index/onboarding",
        "/_index/planejamento",
        "/_index/testes",
        "/_index/zonas-de-treino",
        "/_index/",
        "/_index/calculadora/",
        "/_index/settings/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/_index/clients": {
      "filePath": "_index/clients.tsx",
      "parent": "/_index"
    },
    "/_index/novo-treino": {
      "filePath": "_index/novo-treino.tsx",
      "parent": "/_index"
    },
    "/_index/onboarding": {
      "filePath": "_index/onboarding.tsx",
      "parent": "/_index"
    },
    "/_index/planejamento": {
      "filePath": "_index/planejamento.tsx",
      "parent": "/_index"
    },
    "/_index/testes": {
      "filePath": "_index/testes.tsx",
      "parent": "/_index"
    },
    "/_index/zonas-de-treino": {
      "filePath": "_index/zonas-de-treino.tsx",
      "parent": "/_index"
    },
    "/_index/": {
      "filePath": "_index/index.tsx",
      "parent": "/_index"
    },
    "/_index/calculadora/": {
      "filePath": "_index/calculadora/index.tsx",
      "parent": "/_index"
    },
    "/_index/settings/": {
      "filePath": "_index/settings/index.tsx",
      "parent": "/_index"
    }
  }
}
ROUTE_MANIFEST_END */
